/*
 * @Descripttion: 指令组件
 * @version: 
 * @Author: liujinyuan
 * @Date: 2019-12-29 13:57:55
 * @LastEditors: liujinyuan
 * @LastEditTime: 2020-03-18 09:20:21
 */
import React, { Component } from 'react';
import {View,Text,ScrollView} from 'react-native';
import { Jimi } from '../index';
export default class Instruction extends Component {
    

    constructor(props){
        super(props);
        this.data =[
            {
                type:'arrowButton',
                content:{
                    text:'SOS设置',
                    viceText:'',
                    value:'',
                    id:'1',
                    img:'https://facebook.github.io/react-native/img/tiny_logo.png'
                },
                border:true,
                data:{
                    isButton:true,
                    instruction:'SOS,ins1,ins2,ins3,ins4#',
                    hint:'SOS号码用于接收报警短信以及SOS报警，支持3-20位数字SOS号码设置',
                    instructionArr:[
                        {
                            type:'switch',
                            content:{
                                text:'SOS设置或删除'
                            },
                            value:true,
                            insID:'ins1',
                            insSymmetry:{true:'A',false:'D'},
                            insValue:'A'
                        },
                        {
                            type:'title',
                            content:'',
                        },
                        {
                            type:'input',
                            content:{
                                placeholder:'请输入SOS号码',
                                type:'',
                                text:'号码1',
                                rule:/^[0-9]*[1-9][0-9]*$/
                            },
                            value:'',
                            border:true,
                            insID:'ins2',
                            insValue:'',
            
                        },
                        {
                            type:'input',
                            content:{
                                placeholder:'请输入SOS号码',
                                type:'',
                                text:'号码2',
                                rule:/^[0-9]*[1-9][0-9]*$/
                            },
                            value:'',
                            border:true,
                            insID:'ins3',
                            insValue:'',
            
                        },
                        {
                            type:'input',
                            content:{
                                placeholder:'请输入SOS号码',
                                type:'',
                                text:'号码3',
                                rule:/^[0-9]*[1-9][0-9]*$/
                            },
                            value:'',
                            border:true,
                            insID:'ins4',
                            insValue:'',
            
                        }
                    ]
                }
            },
            {
                type:'arrowButton',
                content:{
                    text:'SOS报警',
                    viceText:'',
                    value:'',
                    id:'3',
                    img:'https://facebook.github.io/react-native/img/tiny_logo.png'
                },
                border:true,
                data:{
                    isButton:true,
                    instruction:'SOSALM,ins1,ins2#',
                    hint:'关闭SOS报警后，设备的SOS按键在按下后不会再触发报警，请谨慎操作',
                    instructionArr:[
                        {
                            type:'switch',
                            content:{
                                text:'SOS报警'
                            },
                            value:true,
                            insID:'ins1,',
                            insSymmetry:{true:'ON,',false:'OFF'},
                            insValue:'ON,',
                        },
                        {
                            contral:0,
                            type:'input',
                            content:{
                                placeholder:'请输入SOS号码',
                                type:'',
                                text:'号码',
                                rule:/^[0-9]*[1-9][0-9]*$/
                            },
                            value:'',
                            border:true,
                            insID:'ins2',
                            insValue:'',
            
                        }
                    ]
                }
            },
            {
                type:'arrowButton',
                content:{
                    text:'位移报警',
                    viceText:'',
                    value:'',
                    id:'5',
                    img:'https://facebook.github.io/react-native/img/tiny_logo.png'
                },
                border:true,
                data:{
                    isButton:true,
                    instruction:'MOVING,ins1,ins2#',
                    hint:'移动半径范围：100~1000 单位：米',
                    instructionArr:[
                        {
                            type:'switch',
                            content:{
                                text:'移动报警'
                            },
                            value:true,
                            insID:'ins1,',
                            insSymmetry:{true:'ON,',false:'OFF'},
                            insValue:'ON,',
                        },
                        {
                            contral:0,
                            type:'input',
                            content:{
                                placeholder:'请填写半径范围单位：米',
                                type:'',
                                text:'半径',
                                rule:/^[0-9]*[1-9][0-9]*$/
                            },
                            value:'',
                            border:true,
                            insID:'ins2',
                            insValue:'',
            
                        }
                    ]
                }
            },
            {
                type:'arrowButton',
                content:{
                    text:'呼叫次数设置',
                    viceText:'',
                    value:'',
                    id:'6',
                    img:'https://facebook.github.io/react-native/img/tiny_logo.png'
                },
                border:true,
                data:{
                    isButton:true,
                    instruction:'CALL,ins1#',
                    instructionArr:[
                        {
                            type:'input',
                            content:{
                                placeholder:'请输入呼叫次数',
                                type:'',
                                text:'半径',
                                rule:/^[0-9]*[1-9][0-9]*$/
                            },
                            value:'',
                            border:true,
                            insID:'ins1',
                            insValue:'',
        
                        }
                    ]
                }
            },
            {
                type:'arrowButton',
                content:{
                    text:'电子狗设置',
                    viceText:'',
                    value:'',
                    id:'6',
                    img:'https://facebook.github.io/react-native/img/tiny_logo.png'
                },
                border:true,
                data:{
                    isButton:true,
                    instruction:'DOG,ins1#',
                    instructionArr:[
                        {
                            type:'switch',
                            content:{
                                text:'电子狗设置'
                            },
                            value:true,
                            insID:'ins1,',
                            insSymmetry:{true:'ON',false:'OFF'},
                            insValue:'ON',
                        }
                    ]
                }
            },
            {
                type:'arrowButton',
                content:{
                    text:'远程控制',
                    viceText:'',
                    value:'',
                    id:'7',
                    img:'https://facebook.github.io/react-native/img/tiny_logo.png'
                },
                border:true,
                data:{
                    isButton:true,
                    instruction:'RELAY,ins1#',
                    instructionArr:[
                        {
                            type:'switch',
                            content:{
                                text:'远程控制'
                            },
                            value:true,
                            insID:'ins1,',
                            insSymmetry:{true:'1',false:'0'},
                            insValue:'1',
                        }
                    ]
                }
            },
            {
                type:'arrowButton',
                content:{
                    text:'震动报警',
                    viceText:'',
                    value:'',
                    id:'8',
                    img:'https://facebook.github.io/react-native/img/tiny_logo.png'
                },
                border:true,
                data:{
                    isButton:true,
                    instruction:'SENALM,ins1,ins2#',
                    instructionArr:[
                        {
                            type:'switch',
                            content:{
                                text:'关闭震动报警'
                            },
                            value:true,
                            insID:'ins1,',
                            insSymmetry:{true:'ON,',false:'OFF'},
                            insValue:'ON<',
                        }
                    ]
                }
            },
            {
                type:'arrowButton',
                content:{
                    text:'超速告警',
                    viceText:'',
                    value:'',
                    id:'8',
                    img:'https://facebook.github.io/react-native/img/tiny_logo.png'
                },
                border:true,
                data:{
                    isButton:true,
                    instruction:'SPEED,ins1,ins2,ins3,ins4#',
                    hint:'速度超出阀值后设备发出报警',
                    instructionArr:[
                        {
                            type:'switch',
                            content:{
                                text:'允许报警'
                            },
                            value:true,
                            insID:'ins1,',
                            insSymmetry:{true:'ON',false:'OFF'},
                            insValue:'ON',
                        },
                        {
                            contral:0,
                            type:'input',
                            content:{
                                placeholder:'持续时间',
                                type:'',
                                text:'半径',
                                rule:/^[0-9]*[1-9][0-9]*$/
                            },
                            value:'',
                            border:true,
                            insID:'ins2',
                            insValue:'',
        
                        },
                        {
                            contral:0,
                            type:'input',
                            content:{
                                placeholder:'超速范围',
                                type:'',
                                text:'半径',
                                rule:/^[0-9]*[1-9][0-9]*$/
                            },
                            value:'',
                            border:true,
                            insID:'ins3',
                            insValue:'',
        
                        },
                        { 
                            type:'title',
                            content:'上报方式',
                        },
                        {
                            contral:0,
                            type:'select',
                            content:[
                                {
                                    text:'平台',
                                    value:'0',
                                    
                                },
                                {
                                    text:'平台加短信',
                                    value:'1',
                                },
                            ],
                            value:'0',
                            border:true,
                            insID:'ins4',
                            insValue:'0',
                        },
                    ]
                }
            },
        ];
    }
    render(){
        return (
            <Jimi.Instruction instructionArr={this.data} onArrowButton={(data) => this.onArrowButton(data)}></Jimi.Instruction>
        );
    }
    onArrowButton = (data) => {
        const params = data.data;
        this.props.navigation.navigate('Instructions',params);
    }
}